micronaut:
  application:
    name: pub
  server:
     port: 8082
cassandra:
  default:
    basic:
      contact-points:
        - localhost:9042
      session-keyspace: exemplo
      load-balancing-policy:
        local-datacenter: datacenter1
nats:
  addresses: ${nats_address:localhost}
  username: ${nats_username:guest}
  password: ${nats_password:guest}

