
version: '3'

services:
  scylla:
    image: scylladb/scylla
    container_name: scylla
    ports:
      - 9042:9042

  jetstream-nats:
    image: synadia/jsm:latest
    entrypoint: /nats-server
    ports:
      - 4222:4222